server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  application:
    name: employee-meal-management-system
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/employee_meal_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  frontend:
    url: ${FRONTEND_URL:http://127.0.0.1:5173}
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    from: ${MAIL_FROM:noreply@company.com}
  meal:
    default-price: 1500.00
    currency: RWF
    timezone: Africa/Kigali

logging:
  level:
    root: INFO
    com.emeal: INFO
    org.springframework.security: INFO
